parameters:
    sensi_yaml_gui.configurator.class: Sensi\Bundle\YamlGuiBundle\Configurator\Configurator

services:
#    sensi_yaml_gui.example:
#        class: %sensi_yaml_gui.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    sonata.block.service.sensi_yaml_gui:
      class: Sensi\Bundle\YamlGuiBundle\Block\YamlGuiDashboardBlockService
      arguments: [ "sonata.block.service.sensi_yaml_gui", @templating ]
      tags:
        - { name: sonata.block }
      calls:
        - [setManagedFiles, [%sensi.yamlgui.managed_files%]]
    sensi_yaml_gui.configurator:
      class: %sensi_yaml_gui.configurator.class%
      arguments: [ %kernel.root_dir% ]
      